[tool.poetry]
name = "hive"
version = "0.0.1"
description = ""
authors = ["Brian Sinkovec <bsin1807@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
