apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: hive-rg
  namespace: crossplane
spec:
  forProvider:
    location: West Europe
    tags:
      provisioner: crossplane
      app: hive