apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hive-ns.yaml

helmCharts:
- name: hive
  repo: https://sinkovec.github.io/DevOps-Hive
  releaseName: hive
  version: 0.1.0
  namespace: hive
  valuesFile: values.yaml