apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

resources:
- sealed-secrets-ns.yaml
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.26.0/controller.yaml