apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: core-composition
spec:
  compositeTypeRef:
    apiVersion: custom-api.example.org/v1alpha1
    kind: my-composite
  resources:
  - name: ResourceGroup
    base:
      apiVersion: azure.upbound.io/v1beta1
      kind: ResourceGroup
      spec:
        forProvider:
          location: West Europe
          tags:
            provisioner: crossplane
  - name: VirtualNetwork
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: VirtualNetwork
      spec:
        forProvider:
          addressSpace:
            - 10.0.0.0/16
          location: West Europe
          resourceGroupNameRef:
            name: core-rg
  - name: Subnet
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: Subnet
      spec:
        forProvider:
          addressPrefixes:
            - 10.0.1.0/24
          resourceGroupNameRef:
            name: core-rg
          virtualNetworkNameRef:
            name: core-vnet
  - name: BlobStorage
    base:
      apiVersion: storage.azure.upbound.io/v1beta1
      kind: Account
      spec:
        forProvider:
          accountKind: BlobStorage
          accountReplicationType: LRS
          accountTier: Standard
          location: West Europe
          resourceGroupNameRef:
            name: core-rg