apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-app
  namespace: argocd
spec:
  project: default
  source:
    chart: hive
    repoURL: https://sinkovec.github.io/DevOps-Hive
    targetRevision: 0.1.0
    helm:
      releaseName: hive
      values: |
        image:
          repository: localhost:5001/sinkovec/hive-app
          pullPolicy: Always
        ingress:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: hive
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    