apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-app
  namespace: argocd
spec:
  project: default
  source:
    chart: hive
    repoURL: https://github.com/sinkovec/DevOps-Hive.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: hive
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    