apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-ns.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
- path: argocd-cm-patch.yaml
  target:
    group: ""
    version: v1
    kind: ConfigMap
    name: argocd-cm