apiVersion: azure.upbound.io/v1beta1
metadata:
  name: default
  namespace: crossplane
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: azure-secret
      key: creds