name: CI pipeline

on: push

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - run: pipx install poetry
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
      with:
        python-version: 3.12
        cache: poetry
    - run: poetry install
    - run: poetry run pylint $(git ls-files '*.py')
    - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
      with:
        dockerfile: ./app/Dockerfile
    - run: poetry run coverage run -m pytest 
    - run: docker buildx build . -t sinkovec/hive-app:latest
    - uses: sonarsource/sonarcloud-github-action@49e6cd3b187936a73b8280d59ffd9da69df63ec9 # v2.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: app/
        args: >
          -Dsonar.organization=devops-hive
          -Dsonar.projectKey=sinkovec_DevOps-Hive
          -Dsonar.sources=hive
          -Dsonar.tests=tests
          -Dsonar.language=py
