name: CI pipeline

on: push

permissions:
  actions: read
  contents: read
  # Needed to upload the results to code-scanning dashboard.
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
    - run: pipx install poetry
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
      with:
        python-version: 3.12
        cache: poetry
    - run: poetry install
    - run: poetry run pylint $(git ls-files '*.py')
    - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
      with:
        dockerfile: ./app/Dockerfile
    - run: poetry run coverage run -m pytest
    - run: poetry run coverage xml
    - uses: sonarsource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216 # v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: app/
        args: >
          -Dsonar.organization=devops-hive
          -Dsonar.projectKey=sinkovec_DevOps-Hive
          -Dsonar.sources=hive
          -Dsonar.tests=tests
          -Dsonar.language=py
          -Dsonar.python.coverage.reportPaths=coverage.xml
  scan-helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
    - uses: tenable/terrascan-action@dd7e921056c6f25b25bff3cf791e063ed7fc3a78 # v1.5.0
      with:
        iac_type: helm
        iac_version: v3
        iac_dir: ./helm
        only_warn: true
        non_recursive: false
        sarif_upload: true
    - uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3.25.8
      with:
        sarif_file: terrascan.sarif
  scan-k8s:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
    - uses: tenable/terrascan-action@dd7e921056c6f25b25bff3cf791e063ed7fc3a78 # v1.5.0
      with:
        iac_type: k8s
        iac_version: v1
        iac_dir: ./k8s
        policy_type: k8s
        only_warn: true
        non_recursive: false
        sarif_upload: true
    - uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3.25.8
      with:
        sarif_file: terrascan.sarif
            
