name: CI pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: poetry
    - run: poetry install
    - run: poetry run pylint $(git ls-files '*.py')
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./app/Dockerfile
    - run: poetry run pytest 
    - run: docker buildx build . -t sinkovec/devops-hive-app:latest


